"""Convert raw COCO-17 poses with MMAction2's validation transforms."""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Literal

import numpy as np

from .constants import (
    CLIP_LEN,
    NUM_CLIPS,
    NUM_JOINTS,
    NUM_PERSONS,
    UNIFORM_SAMPLE_SEED,
)

Stream = Literal['joint', 'joint_motion']


@dataclass(frozen=True)
class PreprocessedSkeleton:
    """One MMAction2-formatted skeleton sample before batch stacking."""

    data: np.ndarray
    frame_indices: np.ndarray
    stream: Stream
    raw_frames: int


def validate_raw_pose(
        keypoints: np.ndarray, keypoint_scores: np.ndarray,
        image_shape: tuple[int, int]) -> tuple[np.ndarray, np.ndarray]:
    """Validate and canonicalize raw pose arrays to `(M,T,17,*)`."""
    keypoints = np.asarray(keypoints, dtype=np.float32)
    keypoint_scores = np.asarray(keypoint_scores, dtype=np.float32)
    if keypoints.ndim == 3:
        keypoints = keypoints[None]
    if keypoint_scores.ndim == 2:
        keypoint_scores = keypoint_scores[None]
    if keypoints.ndim != 4 or keypoints.shape[-2:] != (NUM_JOINTS, 2):
        raise ValueError(
            'keypoints must have shape (T,17,2) or (M,T,17,2); '
            f'got {keypoints.shape}')
    if keypoint_scores.shape != keypoints.shape[:-1]:
        raise ValueError(
            'keypoint_scores must match keypoints (M,T,17); '
            f'got {keypoint_scores.shape} for {keypoints.shape}')
    if not 1 <= keypoints.shape[0] <= NUM_PERSONS:
        raise ValueError(
            f'online inference supports 1..{NUM_PERSONS} person slots; '
            f'got {keypoints.shape[0]}')
    if keypoints.shape[1] < 1:
        raise ValueError('pose sequence has no frames')
    if not np.all(np.isfinite(keypoints)):
        raise ValueError('keypoints contain NaN or infinity')
    if not np.all(np.isfinite(keypoint_scores)):
        raise ValueError('keypoint scores contain NaN or infinity')
    if np.any((keypoint_scores < -1e-6) | (keypoint_scores > 1 + 1e-6)):
        raise ValueError('keypoint scores must lie in [0, 1]')
    if (len(image_shape) != 2 or int(image_shape[0]) <= 0
            or int(image_shape[1]) <= 0):
        raise ValueError(f'invalid image shape: {image_shape}')
    return keypoints, np.clip(keypoint_scores, 0, 1)


class SkeletonPreprocessor:
    """Run the pinned official MMAction2 ST-GCN validation pipeline.

    Motion is intentionally generated by ``GenSkeFeat(feats=['jm'])`` before
    ``UniformSampleFrames``. No local approximation of ``ToMotion`` is used.
    """

    def __init__(self, stream: Stream, logger: logging.Logger | None = None):
        if stream not in ('joint', 'joint_motion'):
            raise ValueError(f'unsupported skeleton stream: {stream}')
        self.stream = stream
        self.logger = logger or logging.getLogger(__name__)

        try:
            from mmaction.utils import register_all_modules
            from mmengine.dataset import Compose
        except ImportError as error:
            raise RuntimeError(
                'MMAction2 v1.2.0 and MMEngine are required for skeleton '
                'preprocessing') from error

        register_all_modules(init_default_scope=True)
        feature = 'j' if stream == 'joint' else 'jm'
        self.pipeline = Compose([
            {'type': 'PreNormalize2D'},
            {
                'type': 'GenSkeFeat',
                'dataset': 'coco',
                'feats': [feature],
            },
            {
                'type': 'UniformSampleFrames',
                'clip_len': CLIP_LEN,
                'num_clips': NUM_CLIPS,
                'test_mode': True,
                'seed': UNIFORM_SAMPLE_SEED,
            },
            {'type': 'PoseDecode'},
            {
                'type': 'FormatGCNInput',
                'num_person': NUM_PERSONS,
                'mode': 'zero',
            },
        ])

    def __call__(
            self, keypoints: np.ndarray, keypoint_scores: np.ndarray,
            image_shape: tuple[int, int]) -> PreprocessedSkeleton:
        keypoints, keypoint_scores = validate_raw_pose(
            keypoints, keypoint_scores, image_shape)
        raw_frames = int(keypoints.shape[1])
        results = self.pipeline({
            'keypoint': keypoints.copy(),
            'keypoint_score': keypoint_scores.copy(),
            'total_frames': raw_frames,
            'start_index': 0,
            'img_shape': (int(image_shape[0]), int(image_shape[1])),
            'original_shape': (int(image_shape[0]), int(image_shape[1])),
        })
        if results is None:
            raise RuntimeError('MMAction2 skeleton pipeline returned None')
        data = np.asarray(results['keypoint'], dtype=np.float32)
        expected = (NUM_CLIPS, NUM_PERSONS, CLIP_LEN, NUM_JOINTS, 3)
        if data.shape != expected:
            raise RuntimeError(
                f'{self.stream} pipeline produced {data.shape}, expected '
                f'{expected}')
        if not np.all(np.isfinite(data)):
            raise RuntimeError(
                f'{self.stream} pipeline produced NaN or infinity')
        frame_indices = np.asarray(results['frame_inds'], dtype=np.int64)
        if frame_indices.shape != (CLIP_LEN,):
            raise RuntimeError(
                f'expected {CLIP_LEN} sampled indices, got '
                f'{frame_indices.shape}')
        self.logger.info(
            '%s preprocessing: raw=%s -> sample=%s -> batched=%s',
            self.stream, keypoints.shape, data.shape, (1, *data.shape))
        return PreprocessedSkeleton(
            data=np.ascontiguousarray(data),
            frame_indices=frame_indices,
            stream=self.stream,
            raw_frames=raw_frames,
        )


def window_slices(
        total_frames: int, window_frames: int = CLIP_LEN,
        stride: int = CLIP_LEN // 2) -> list[tuple[int, int]]:
    """Return overlapping raw-frame windows with complete tail coverage."""
    if total_frames < 1:
        raise ValueError('total_frames must be positive')
    if window_frames < 1:
        raise ValueError('window_frames must be positive')
    if not 1 <= stride <= window_frames:
        raise ValueError('stride must be in [1, window_frames]')
    if total_frames <= window_frames:
        return [(0, total_frames)]
    starts = list(range(0, total_frames - window_frames + 1, stride))
    tail_start = total_frames - window_frames
    if starts[-1] != tail_start:
        starts.append(tail_start)
    return [(start, start + window_frames) for start in starts]


def pose_arrays_from_payload(
        payload: dict) -> tuple[np.ndarray, np.ndarray, tuple[int, int]]:
    """Extract canonical arrays and image shape from a pose pickle payload."""
    metadata = payload.get('metadata', {})
    try:
        image_shape = (int(metadata['height']), int(metadata['width']))
        keypoints = payload['keypoint']
        keypoint_scores = payload['keypoint_score']
    except (KeyError, TypeError, ValueError) as error:
        raise ValueError('invalid extracted-pose payload') from error
    keypoints, keypoint_scores = validate_raw_pose(
        keypoints, keypoint_scores, image_shape)
    return keypoints, keypoint_scores, image_shape
